[RAP-90] Add loading fights and players data by JSON endpoint
GCyganek/rapier-app pull request #29
Opened 2022-05-10 08:14 UTC by m-wojnar

Zaimplementowano importowanie walk oraz zawodników przez prosty endpoint REST. Metodą POST wysyła się w body odpowiedni string w formacie JSON (dokładny opis w dokumentacji endpointów i definicji interfejsów). Dane zostają wstawione do słowników 'fights' oraz 'players' zawierających odpowiednio walki i zawodników w serwisach FightsService oraz PlayersService.

2022-05-10 14:39 UTC, rynkow requested changes
Według mnie jest ok, ale można by jeszcze  sprawdzać czy podane id nie są już zajęte. Aktualnie da się nadpisać walki (w przypadku zawodników unikalność id jest sprawdzana w metodzie newPlayer)

2022-05-10 19:57 UTC, GCyganek commented
Imo jest w porządku, nie ma się do czego przyczepić

2022-05-10 19:58 UTC, GCyganek approved these changes

2022-05-11 06:38 UTC, rynkow approved these changes

2022-05-11 10:49 UTC, merged