changed sequence logic
GCyganek/rapier-app pull request #33
Opened 2022-05-12 22:18 UTC by karpinsk

Zmieniłem logikę komponentu sekwencji - teraz działa zgodnie z logiką, zatwierdzoną przez klienta. 
Mam jednak problem z Remisem - po kliknięciu na niego wszystkie przyciski muszą być wyłączone, a jedyną opcją dla użytkownika byłoby albo się cofnąć (strzałką albo usuwaniem całego ciągu, który składa się z samego napisu "Remis"), albo zaproponować punkty. Nie wiem jednak, jak zrobić binding dla tych przycisków - może na spotkaniu to omówimy.

2022-05-13 09:27 UTC, Dewkong requested changes
Tak jak pisałeś jest problem z tymi przyciskami na dole, np. jak klikniemy remis, to zablokujemy możliwość klikania sekwencji, a możemy wcisnąć "Usuń ciąg" i zostajemy wtedy bez żadnej sekwencji i bez możliwości klikania. Musimy to przegadać na spotkaniu.

2022-05-13 15:16 UTC, closed without merging

2022-05-14 10:36 UTC, robertkbk reviewed
Dalej brakuje tej współpracy z JSON'em

2022-05-14 10:36 UTC, robertkbk commented on client/src/routes/fight/fight-sequence-components/SelectAction.svelte
> +        opacity: 0.3;
Myślę, że są lepsze sposoby na pokazanie, że przycisk jest wyłączony niż zmiana `opacity`, przy okazji można dodać szybkie `transition`

2022-05-14 10:36 UTC, robertkbk commented on client/src/routes/fight/fight-sequence-components/SelectColour.svelte
>          height: 100%;
Może warto by pomyśleć o `display: flex` wraz ze `stretch` na przyciskach + `gap`, żeby komponenty się automatycznie rozmieszczały niezależnie od ilości przycisków?

2022-05-14 10:36 UTC, robertkbk commented on client/src/routes/fight/fight-sequence-components/SelectColour.svelte
> +        font-size: calc(8px + 1.5vw);
Jak już bardzo chcesz responsywnego fonta, to daj przynajmniej coś w rodzaju `clamp(1rem, .5rem + 1.5vw, 3rem)`