Rap 109 implementacja przesylania propozycji
GCyganek/rapier-app pull request #51
Opened 2022-06-04 15:08 UTC by karpinsk

Komunikacja pomiędzy bocznymi a głównym jest gotowa - back i front są połączone :)

Zauważyłem, że mamy dwa komponenty o nazwie FightPropositionDetails - jeden jest oknem modalnym, a drugi składową komponentu FightSideProposition. Nie jestem pewien, czy tak miało być, zakładam że jak Krystian tworzył okno modalne dla propozycji to przez przypadek dał taką samą nazwę. Nie powoduje to kolizji nazw, bo są w różnych folderach, ale utrudnia analizę.

2022-06-05 12:08 UTC, Dewkong reviewed
Jeśli chodzi o funkcjonalności, to wszystko działa poprawnie - od sędziów bocznych jestem w stanie przesłać propozycje, sędzia główny może zobaczyć ich szczegóły i zatwierdzić/odrzucić ich propozycje. Działają również case'y takie jak:
- główny otrzymuje propozycje od czerwonego i niebieskiego
- jeśli boczny wyśle drugą propozycję, to ta poprzednia zostaje nadpisana (tak chcieliśmy żeby działało)

Wydaje mi się, że przydałoby się jeszcze wystylować jakoś komponent, kiedy nie przyszła żadna informacja od bocznego (aktualnie to jest po prostu tekst). 

Moim zdaniem brakuje chyba też możliwości wyjścia z ekranu szczegółów propozycji bez podejmowania decyzji. Chodzi mi o to, że kiedy główny kliknie na propozycję, dostaje okno modalne gdzie ma tylko opcje ODRZUĆ albo ZATWIERDŹ - obydwie opcje kasują propozycję bocznego, ale tylko ZATWIERDŹ akceptuje ciąg zdarzeń. Co w sytuacji kiedy główny kliknął przypadkiem w szczegóły albo chciał tylko podejrzeć co boczny podesłał i jeszcze nie podejmuje decyzji? Najlepszym rozwiązaniem chyba by było dodanie możliwości kliknięcia na to szare tło dookoła i wtedy okno modalne po prostu się zamknie, bez odrzucania/zatwierdzania propozycji. Ewentualnie można dodać przycisk do zamknięcia, ale chyba wolałbym po prostu kliknąć obok okienka.

A co do struktury komponentów, to szczerze mówiąc sam nie wiem czemu tam powstały takie duplikaty. Wydawało mi się, że ustaliliśmy:
Fight -> FightSideProposition (z dwoma przyciskami które odpalają okna modalne) -> FightPropositionDetails (okno modalne)
Z tego co widzę to tam teraz FightSideProposition składa się z dwóch przycisków, które są komponentami i nazywają się tak samo jak komponent okna modalnego. A okno modalne to teraz nowy komponent FightSuggestion? Mógłbyś Vadim wytłumaczyć jak wygląda teraz to złożenie komponentów od Fight? Czy ten komponent okna modalnego FightPropositionDetails jest gdziekolwiek użyty? (IntelliJ podpowiada mi, że nie)

2022-06-05 13:04 UTC, robertkbk requested changes

2022-06-05 13:04 UTC, robertkbk commented on client/src/model/Communication.ts
> +    events: Batch[];
Specjalnie nie użyłem tutaj `Batch`, żeby dokładniej odwzorować dane przychodzące z backendu.
Ta zmiana psuje strukturę klas w `Communication` , bo dodaje zależność od klasy zdefiniowanej na potrzeby komponentu. Proponuję albo przywrócić zmianę i dostosować odpowiednio `Batch` i `FightEvent`, albo przenieść `Batch` (przy okazji zmienić nazwę na coś bardziej wymownego) do katalogu zawierającego model. Problem z drugim rozwiązaniem jest taki, że `Batch` obecnie nie odwzorowuje dokładnie danych przychodzących z backendu (zawiera dodatkowe pola).

2022-06-05 13:04 UTC, robertkbk commented on client/src/routes/FightSocket.ts
> +import type { Batch } from './fight/fight-sequence-components/Batch';
Ponownie, `Batch` powinien albo być elementem modelu, albo zamknięty do użytku w komponentach

2022-06-05 13:04 UTC, robertkbk commented on client/src/routes/FightSocket.ts
> +      switch (response.judgeColor.toUpperCase()) {
To trochę no-op, bo dane z backu już przychodzą uppercase. Do tego zmienia to typ z `Response.Color` na `string`

2022-06-05 13:04 UTC, robertkbk commented on client/src/routes/FightSocket.ts
> +    this.socket.on(Events.EventsSuggestion, listener);
Przy założeniu, że wywołamy `awaitSuggestions` tylko raz, jest ok

2022-06-05 13:04 UTC, robertkbk commented on client/src/routes/FightSocket.ts
> +    }
Może:
```js
this.socket.emit(this.role === 'MAIN' ? Events.NewEvents : Events.EventsSuggestion. eventsParameters);
```

2022-06-05 13:04 UTC, robertkbk commented on client/src/routes/fight/FightPropositionDetails.svelte
> +    import { Label } from "@smui/button";
Jeżeli dobrze pamiętam, mieliśmy odejść od używania `smui`

2022-06-05 13:04 UTC, robertkbk commented on client/src/routes/fight/FightPropositionDetails.svelte
> +                style="background-color: {suggestion.judgeColor.toLowerCase()==="red" ? 'var(--red-fighter)' : 'var(--blue-fighter)'}"
Niepotrzebny `toLowerCase`.
Chyba, że
```js
`var(--${suggestion.judgeColor.toLowerCase()}-fighter)`
```

2022-06-05 13:04 UTC, robertkbk commented on client/src/routes/fight/FightSideProposition.svelte
> +    height: 20vh;
Wysokość tego elementu powinna być określona przez layout `grid` elementu nadrzędnego.

2022-06-07 19:11 UTC, karpinsk commented on client/src/routes/FightSocket.ts
> +      switch (response.judgeColor.toUpperCase()) {
Może czegoś nie rozumiem, ale z backu prawdopodobnie dostajemy string lowercase:

![server](https://user-images.githubusercontent.com/96959703/172463118-3d13c340-d1e7-4029-9293-045177616821.png)
![zxcasd](https://user-images.githubusercontent.com/96959703/172463188-11aa5b8c-54fa-4027-a8a0-29b831a9a43c.png)

2022-06-07 19:15 UTC, karpinsk commented on client/src/routes/FightSocket.ts
> +    this.socket.on(Events.EventsSuggestion, listener);
A może być tak, że w ramach pojedynczej walki wywołamy `awaitSuggestions` wielokrotnie?

2022-06-07 19:16 UTC, karpinsk commented on client/src/routes/FightSocket.ts
> +    }
Słuszna uwaga, wygląda lepiej, dzięki!

2022-06-07 19:17 UTC, karpinsk commented on client/src/routes/fight/FightPropositionDetails.svelte
> +    import { Label } from "@smui/button";
Zgadza się. Co prawda nawet nie była używana, tylko import został, ale już usunięte

2022-06-08 09:44 UTC, karpinsk commented on client/src/model/Communication.ts
> +    events: Batch[];
Zmieniłem nazwę i przeniosłem do modelu.

2022-06-08 09:52 UTC, karpinsk commented on client/src/routes/fight/FightPropositionDetails.svelte
> +                style="background-color: {suggestion.judgeColor.toLowerCase()==="red" ? 'var(--red-fighter)' : 'var(--blue-fighter)'}"
Podczas rozmowy zmieniłem na "RED" i błąd zniknął, jednak warunek `suggestion.judgeColor=="RED"` jest zawsze nie spełniony.
Dlatego konwertuję na stringa i porównuję z `"red"`.

2022-06-08 15:08 UTC, robertkbk approved these changes

2022-06-08 16:48 UTC, merged