Rap 33 fight end conditions
GCyganek/rapier-app pull request #8
Opened 2022-04-16 18:49 UTC by GCyganek

- implementacja wzorca Observer, aby Timer dla danego pojedynku mógł przesłać powiadomienie o zakończeniu założonego czasu trwania pojedynku do FightsService
- implementacja wzorca Observer, aby FightsService mógł poinformować JudgesGateway o spełnieniu jednego z warunków zakończenia danego pojedynku
- JudgesGateway przy otrzymaniu informacji o spełnieniu warunku zakończenia pojedynku przesyła sędziom informujący o tym event (FightsService powiadamiający o spełnieniu tych warunków gwarantuje przez fightEndNotified, że JudgesGateway nie będzie rozsyłał tych eventów za każdym razem przy sprawdzaniu warnuków zakończenia po tym, gdy zostały spełnione)
- dodanie testów dla wszystkich zaimplementowanych metod

2022-04-18 09:05 UTC, m-wojnar requested changes
Super pomysł z zastosowaniem wzorca observer! Rozwiązanie z powiadomieniami jest eleganckie i łatwe w zrozumieniu. Proponuję głównie tylko dwie zmiany:

1. Może da się zastąpić dwa rodzaje observerów jednym? Mam na myśli użycie FightEndConditionFulfilled w miejscach FightTimeEded. Wydaje mi się, że mogłoby to uprościć kod. Jeśli jednak jest to celowy zabieg i połączenie tych klas nie ma sensu albo mogłoby dziwnie skomplikować kod, to nie warto.
2. Uważam, że w walce warto dodać informację o tym, jaki warunek zakończenia nas interesuje i dodać obsługę tego w kodzie. Może to być na przykład zbiór albo lista zdarzeń, na ten moment przykładowe warunki zakończenia to [time, points], [time], [points], [] (puste!). Dlatego warto sprawdzać czy dany warunek w ogóle nas interesuje i wysyłać powiadomienia tylko o istotnych dla tej walki warunkach.

2022-04-18 09:05 UTC, m-wojnar commented on server/src/classes/timer/timer.class.ts
>        timeInMinutes * TimerConstants.MILLISECONDS_IN_MINUTE;
Może umieścimy tę stałą jako pole w tej klasie? Wtedy nie będzie trzeba tworzyć specjalnie jednolinijkowej klasy z jednym polem

2022-04-18 09:05 UTC, m-wojnar commented on server/src/interfaces/fight.interface.ts
> +
Przydałoby się pole, które zawiera informację o tym, jaki jest warunek zakończenia pojedynku, ponieważ nie zawsze to będzie dana liczba punktów, tylko na przykład sam czas. Wtedy trzeba będzie też odpowiednio dostosować kod, aby serwer wysyłał powiadomienia tylko dla warunków zakończenia zapisanych w tym polu (właściwie może to być zbiór albo lista, bo możliwe, że jest jednocześnie kilka warunków zakończenia).

2022-04-18 09:05 UTC, m-wojnar commented on server/src/interfaces/observers/fight-time-ended-observer.interface.ts
> +}
Może da się nieco uprościć kod i zrobić to za pomocą jednego observera, a nie dwóch? Wydaje mi się, że FightEndConditionFulfilledObserver powinien być w stanie wypełnić funkcjonalność FightTimeEndedObserver.

2022-04-18 09:05 UTC, m-wojnar commented on server/src/interfaces/publishers/fight-time-ended-publisher.interface.ts
> +}
Analogicznie tutaj - FightEndConditionFulfilledPublisher powinien być w stanie wypełnić funkcjonalność FightTimeEndedPublisher

2022-04-18 09:05 UTC, m-wojnar commented on server/src/services/fights.service.ts
> +      fight.bluePlayer.points >= fight.pointsToEndFight
Tutaj trzeba będzie sprawdzić czy w tej walce w ogóle jest warunek zakończenia daną liczbą punktów, a nie na przykład sam czas.

2022-04-18 09:05 UTC, m-wojnar commented on server/src/services/fights.service.ts
> +    fight.timer.addFightTimeEndedObserver(this);
Tutaj trzeba sprawdzić czy w tej walce jest warunek zakończenia przez określoną liczbą czasu, a nie same punkty.

2022-04-18 09:19 UTC, GCyganek commented on server/src/interfaces/observers/fight-time-ended-observer.interface.ts
> +}
Myślałem nad tym i rozbiłem na dwa, bo wydawało mi się że tak będzie czytelniej i nie będzie opcji wysłania powiadomienia z Timera o spełnieniu warunków punktowych pojedynku (co nie jest możliwe przy obecnym kodzie - i dobrze), ale być może rzeczywiście można zostawić ten jeden observer i pilnować się, żeby wysyłane do observerów condition z Timera dotyczyło czasu. Zrobi się test, żeby mieć pewność, że w przyszłości ktoś tego przez przypadek nie zmieni i powinno być w porządku. Tak zrobię

2022-04-18 09:20 UTC, GCyganek commented on server/src/interfaces/fight.interface.ts
> +
Rzeczywiście nie pomyślałem o tym, będzie dodane

2022-04-19 11:11 UTC, m-wojnar requested changes
Wszystko w porządku, wprowadzono omawiane zmiany. Dodam jeszcze jeden commit z refactoringiem kodu

2022-04-19 14:21 UTC, m-wojnar approved these changes
Zmiany zaakceptowane

2022-04-19 14:21 UTC, merged